# Generated by Django 2.2.10 on 2020-06-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=250, verbose_name='Путь к файлу')),
            ],
            options={
                'verbose_name': 'Путь к файлу',
                'verbose_name_plural': 'Пути к файлу',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя столбца')),
                ('width', models.IntegerField(verbose_name='Ширина столбца')),
                ('ordinal', models.IntegerField(verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Поле таблицы',
                'verbose_name_plural': 'Поля таблицы',
            },
        ),
    ]
