# Generated by Django 2.2.10 on 2020-06-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='ordinal',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='table',
            name='width',
            field=models.IntegerField(default=1, verbose_name='Ширина столбца'),
        ),
    ]
