# Generated by Django 2.2.10 on 2020-06-02 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20200602_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['ordinal'], 'verbose_name': 'Поле таблицы', 'verbose_name_plural': 'Поля таблицы'},
        ),
    ]
