# Generated by Django 2.2.10 on 2020-05-26 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='genre',
        ),
        migrations.AlterField(
            model_name='author',
            name='phone',
            field=models.CharField(max_length=256, verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='Articleship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(verbose_name='Основной')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.Article', verbose_name='Статья')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.Genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр статьи',
                'verbose_name_plural': 'Жанры статьи',
                'ordering': ('-is_main', 'genre__name'),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='genre',
            field=models.ManyToManyField(through='articles.Articleship', to='articles.Genre'),
        ),
    ]
